# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Slack Docs
nav:
  - Home: "index.md"
  - How to Add Your Name's Pronunciation to your Profile: "EditProfile.md"
  - How to Send a File Through Direct Message(DM): "SendAFileDM.md"
  - How to Mark a Message Unread and Set a Reminder: "MarkUnread.md"
  - Troubleshooting: "trouble.md"
  - Glossary: "glossary.md"
theme: 
  name: material
  custom_dir: overrides
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_css:
  - stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - sane_lists
  - attr_list
  - md_in_html